name: Bug Report
description: Report a bug to help us improve Hytools.
title: '[Bug] title'
labels: bug
body:

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the issue is.
        Provide as much information as possible.
    validations:
      required: true
  - type: textarea
    id: replication
    attributes:
      label: Describe how to replicate bug
      description: |
        Please provide a step-by-step explanation on how to reproduce the bug.
        Make sure to test your replication steps.
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date of submittion
    validations:
      required: true
  - type: input
    id: java
    attributes:
      label: Your java version
    validations:
      required: true
  - type: input
    id: context
    attributes:
      label: Your operating system and the version
    validations:
      required: true
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Before submitting a bug report
      options:
        - label: |
            This bug wasn't already reported.
            (I have checked every bug report on GitHub)
          required: true
        - label: |
            I agree to this repository's prerequisites.
            (I have read and agree to the License, Code of Conduct, and Contributing Guidelines)
          required: true